# BOB Google Maps V3.0 - Configuration File
# Author: Divyanshu Singh Chouhan
# Release: October 3, 2025

# Extractor Configuration
extractor:
  # Browser settings
  headless: true
  timeout: 60
  page_load_timeout: 90

  # Retry settings
  max_retries: 3
  retry_delay: 2

  # Stealth settings
  stealth_mode: true

  # Network settings
  intercept_network: true
  block_resources: true
  blocked_resource_types:
    - image
    - stylesheet
    - font
    - media

  # Data extraction
  max_reviews: 10
  max_images: 20
  include_reviews: true
  include_images: true

  # Quality thresholds
  min_quality_score: 50

# Cache Configuration
cache:
  enabled: true
  cache_db_path: "bob_cache_ultimate.db"
  expiration_hours: 24
  auto_cleanup: true
  cleanup_days: 7
  max_cache_size_mb: 500

# Parallel Processing Configuration
parallel:
  enabled: true
  max_concurrent: 10
  context_pool_size: 5
  max_memory_mb: 2048
  max_cpu_percent: 80
  batch_size: 100
  checkpoint_interval: 10

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/bob.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_file_size_mb: 10
  backup_count: 5

# Paths
paths:
  cache_dir: "./cache"
  logs_dir: "./logs"
  data_dir: "./data"
  exports_dir: "./exports"
