[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bob-google-maps"
version = "0.4.0"
authors = [
    {name = "Divyanshu Singh Chouhan", email = "divyanshu@abcsteps.com"},
]
description = "BOB Google Maps – Build Online Business toolkit"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
dependencies = [
    "selenium>=4.0.0",
    "tqdm>=4.60.0",
    "pydantic>=2.0.0",
    "playwright>=1.40.0",
    "textblob>=0.17.0",
]

[tool.setuptools.packages.find]
include = ["bob_core*"]
exclude = ["legacy*", "tests*"]

[project.scripts]
bob = "bob_core:cli" 