global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'bob-api'
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ['bob-api:8000'] 